### ISSUE TITLE
compile with erlang 18 / Elixir 1.0.4

### ISSUE THREAD

**Issue by binarytemple** [inaka/ikbot#12]
Quite a number of compilation failures, I modified the mix.esx file to the following, changed a bunch of erlang:now() to erlang:timestamp() and recompiled:

```
defmodule Ikbot.Mixfile do
  use Mix.Project

  def project do
    [
      app: :ikbot,
      version: "0.0.1",
      elixir: "1.0.4",
      deps: deps
    ]
  end

  def application do
    [
      applications: [
        :httpotion,
        :hedwig
      ],
      mod: {Ikbot, []},
      env: []
    ]
  end

  defp deps do
    [
      {:jsx, github: "talentdeficit/jsx"},
      {:ibrowse, github: "cmullaparthi/ibrowse"},
      {:httpotion, "~> 0.2.0"},
      {:hedwig, github: "scrogson/hedwig"},
      {:pong, github: "inaka/pong", branch: "elbrujohalcon.rank", compile: "", app: false},
      {:exredis, github: "artemeff/exredis"}
    ]
  end
end
```

But now I'm stuck again, I'm receiving this compile error:

```
mix compile 

....elided... ... 
Compiled lib/ikbot/scripts/xkcd.ex
Compiled lib/ikbot/scripts/news.ex
lib/ikbot/ikbot_hipchat.ex:3: warning: undefined module attribute @usage, please remove access to @usage or explicitly set it to nil before access

== Compilation error on file lib/ikbot/scripts/pivotal.ex ==
** (UndefinedFunctionError) undefined function: Exredis.Api.__using__/1
    Exredis.Api.__using__([])
    lib/ikbot/scripts/pivotal.ex:2: (module)
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```

Quite new to the language. Any ideas?
